[project]
name = "fastapi-pathao-sdk"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.117.1",
    "pydantic-settings>=2.10.1",
    "uvicorn>=0.37.0",
]
